version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo apt-get clean
      - sudo apt-get update
      - sudo apt-get install nginx -y 

  build: 
    commands:
      - echo Build Started on `date`
      - cp index.html /var/www/html/
      - cp -rav assets /var/www/html/
      - cp -rav error /var/www/html/
      - cp -rav images /var/www/html/
      - cp -rav appspec.yml /var/www/html
      - cp -rav scripts /var/www/html/

  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    # - /var/www/html/index.html
    # - /var/www/html/assets/**/* 
    # - /var/www/html/error/**/*
    # - /var/www/html/images/**/* 
    # - /var/www/html/appspec.yml
    # - /var/www/html/scripts/**/*
    - '**/*'
    
